name: Run Dynatrace Export
# This workflow runs on a Friday morning.
# It extracts the current configuration of Dynatrace
# and commits it to source control

on:
  schedule:
    # Run at 10:21 on on a Friday
    # 21 minutes past to avoid the on the hour surge in demand
    - cron:  '21 10 * * 5'
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create new branch
        run: |
          NOW=$(date +"%Y-%m-%d")
          git checkout -b f/dynatrace-export-$NOW
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.4
      - name: Run export
        run: |     
          export DYNATRACE_TARGET_FOLDER=../infrastructure
          export DYNATRACE_ENV_URL=${{ secrets.DYNATRACE_PROD_ENV_URL }}
          export DYNATRACE_API_TOKEN=${{ secrets.DYNATRACE_PROD_API_TOKEN}}
          cd terraform
          terraform init -backend=false
          .terraform/providers/registry.terraform.io/dynatrace-oss/dynatrace/1.44.0/linux_amd64/terraform-provider-dynatrace_v1.44.0 -export
      - name: Commit Dynatrace Export Changes
        run: |
          NOW=$(date +"%Y-%m-%d")
          mkdir .ssh
          cat <<< "${{ secrets.REPO_KEY }}" > .ssh/key
          chmod 600 .ssh/key
          eval `ssh-agent -s`
          ssh-add .ssh/key
          git config --local user.email ${{ secrets.OBSERVABILITY_TEAM_EMAIL }}
          git config --local user.name "Observability"
          git remote set-url origin git@github.com:govuk-one-login/observability-dynatrace-resources.git
          git commit -am "Automated: Dynatrace export for $NOW"
          git push --set-upstream origin f/dynatrace-export-$NOW